# Generated by Django 5.2 on 2026-09-03 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title_role',
            field=models.CharField(blank=True, db_index=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/unknown', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_city',
            field=models.CharField(blank=True, db_index=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_country',
            field=models.CharField(blank=True, db_index=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, default='No summary available'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['job_title_role'], name='profiles_pr_job_tit_f539b7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['location_country'], name='profiles_pr_locatio_3aa265_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['location_city'], name='profiles_pr_locatio_95e0f3_idx'),
        ),
    ]
