# Generated by Django 5.2 on 2026-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_full_name_alter_profile_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
